---
collections:
  - name: community.docker
  - name: community.postgresql
  - name: https://github.com/hyphacoop/ansible-common.git
    type: git
    version: 870ee7f77f5f6bd3102d4180af6b24497aa5ac26
roles:
  - src: geerlingguy.docker
  - src: geerlingguy.nodejs
