---
- name: check if cargo is installed
  shell: command -v cargo
  register:  cargo_exists
  ignore_errors: yes
  become_user: "{{rust_user}}"

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
  become_user: "{{rust_user}}"


- name: install rust/cargo
  when: cargo_exists is failed
  shell: /bin/bash /tmp/sh.rustup.rs -y
  tags:
    - rust
  become_user: "{{rust_user}}"

