---
### General Regen settings
regen_user: regen
regen_user_home: "/home/{{regen_user}}"
regen_home: "{{regen_user_home}}/.regen"
regen_home_autoclear: false
regen_unsafe_reset: false
regen_version: v3.0.0
regen_repository: https://github.com/regen-network/regen-ledger.git
regen_bin: "{{ regen_user_home }}/go/bin/regen"
regen_service_name: "regen"
regen_bond_denom: "uregen"
regen_gov_testing: false
regen_voting_period: 10s
chain_id: "testnet"


### Default variables for creating a validator
regen_create_validator: false
regen_gentx_validator_stake: "10000000uregen"
regen_validator_keyring: "test"
regen_validator_coins: "1000000000000uregen"

### Default variables for airdropping tokens
regen_airdrop: false
regen_airdrop_coins: "1000000000uregen"
regen_airdrop_accounts: []

### Cosmovisor settings
# TODO: Support arbitrary cosmovisor branches
use_cosmovisor: true
cosmovisor_version: v1.0.0
cosmovisor_repository: github.com/cosmos/cosmos-sdk/cosmovisor/cmd/cosmovisor
cosmovisor_bin: "{{regen_user_home}}/go/bin/cosmovisor"
cosmovisor_home: "{{ regen_home }}/cosmovisor"
cosmovisor_service_name: "cosmovisor"
cosmovisor_skip_backup: true

### Go configuration
go_arch: "linux-amd64"
go_version: "1.18.3"

### config.toml variables
node_moniker: "node"
fast_sync: true
abci: socket

### RPC
rpc_port: '26657'

### P2P
p2p_port: '26656'
p2p_external_address: ''
p2p_seeds: ''
p2p_persistent_peers: ''
p2p_upnp: false
p2p_pex: true
p2p_seed_mode: false
p2p_private_peer_ids: false

### Statesync
statesync_enabled: false
statesync_rpc_servers: ''
statesync_trust_height: 0
statesync_trust_hash: ''
statesync_trust_period: 168h0m0s
statesync_discovery_time: 15s
statesync_chunk_request_timeout: 10s
statesync_auto_populate: true
# TODO: Why does my config say 4 when it isn't default?
statesync_chunk_fetchers: '4'

### Fastsync
fastsync_version: v0
# TODO: All the other fastsync versions?

prometheus_enabled: false
prometheus_listen_addr: :26660
instrumentation_namespace: tendermint

### app.toml variables
minimum_gas_prices: ''
pruning: default
pruning_keep_recent: '0'
pruning_keep_every: '0'
pruning_interval: '0'
halt_height: '0'
halt_time: '0'
min_retain_blocks: '0'
inter_block_cache: true

### telemetry
telemetry_service_name: ''
telemetry_enabled: false
telemetry_enable_hostname: false
telemetry_enable_hostname_label: false
telemetry_enable_service_label: false
prometius_retention_time: '0'

## API
api_enabled: false
api_swagger: false
api_port: '1317'

### grpc
grpc_enabled: true
grpc_port: '9090'

### state-sync
statesync_snapshot_interval: 0
statesync_snapshot_keep_recent: 2

#### client.toml variables
client_keyring_backend: os
client_broadcast_mode: sync

### Faucet settings
faucet_enabled: false
faucet_service_name: token-faucet
faucet_port: '8000'

### node exporter config
node_exporter_port: 9100

### Prometheus / Grafana defaults
grafana_ssh_url: root@monitor.polypore.xyz
monitoring_prometheus: false

### PANIC monitoring defaults
panic_ssh_url: root@monitor.polypore.xyz
monitoring_panic: false
panic_config_file: /home/panic/panic_cosmos/config/user_config_nodes.ini
panic_is_validator: 'no'
panic_include_in_node_monitor: 'yes'
panic_include_in_network_monitor: 'yes'

### Reboot after setup
reboot: true

# Vars with no defaults (to prevent code from running)
# These don't get put into config files
# genesis_url: ""
# genesis_file: ""
# addrbook_file: ""
# addrbook_url: "https://quicksync.io/addrbook.cosmos.json"
# node_key_file: ""
# priv_validator_key_file
