---
- name: Set variables for api endpoint
  set_fact:
    endpoint_port: '{{api_port}}'
    site_hostname: '{{chain_api_host}}.{{inventory_hostname}}'
  when: chain_use_ssl_proxy | default(false) | bool

- name: Setup nginx SSL for chain api endpoint
  include_role:
    name: nginx-ssl
  when: chain_use_ssl_proxy | default(false) | bool

- name: Set variables for rpc endpoint
  set_fact:
    endpoint_port: '{{rpc_port}}'
    site_hostname: '{{chain_rpc_host}}.{{inventory_hostname}}'
  when: chain_use_ssl_proxy | default(false) | bool

- name: Setup nginx SSL for chain rpc endpoint
  include_role:
    name: nginx-ssl
  when: chain_use_ssl_proxy | default(false) | bool

- name: Set variables for GRPC endpoint
  set_fact:
    endpoint_port: '{{grpc_port}}'
    site_hostname: '{{chain_grpc_host}}.{{inventory_hostname}}'
    grpc_vhost: true
  when: chain_use_ssl_proxy | default(false) | bool

- name: Setup nginx SSL for chain GRPC endpoint
  include_role:
    name: nginx-ssl
  when: chain_use_ssl_proxy | default(false) | bool

- name: Set variables for P2P endpoint
  set_fact:
    endpoint_port: '{{p2p_port}}'
    site_hostname: '{{chain_p2p_host}}.{{inventory_hostname}}'
  when: chain_use_ssl_proxy | default(false) | bool

- name: Setup nginx SSL for chain P2P endpoint
  include_role:
    name: nginx-ssl
  when: chain_use_ssl_proxy | default(false) | bool
