---

- name: "Run docker image for Hasura"
  community.docker.docker_container:
    state: started
    name: big-dipper-hasura
    image: "hasura/graphql-engine:{{hasura_version}}"
    network_mode: host
    restart_policy: "always"
    env:
      HASURA_GRAPHQL_DATABASE_URL: "{{bigdipper_db_url}}"
      HASURA_GRAPHQL_SERVER_PORT: "{{ hasura_port | string }}"
      HASURA_GRAPHQL_SERVER_HOST: "127.0.0.1"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      ACTION_BASE_URL: "http://localhost:{{bdjuno_hasura_actions_port}}"
      HASURA_GRAPHQL_ADMIN_SECRET: "{{hasura_admin_secret}}"

- name: "Set up node+npm"
  include_role:
    name: geerlingguy.nodejs

- name: "Set up hasura CLI"
  shell: "npm install --unsafe-perm --global hasura-cli@{{hasura_cli_version}}"

- name: Wait for docker to be ready
  wait_for:
    port: "{{hasura_port}}"
    delay: 10

- name: "Apply metadata to hasura"
  become_user: "{{bigdipper_user}}"
  shell: |
    hasura metadata apply --endpoint http://localhost:{{hasura_port}} --admin-secret "{{hasura_admin_secret}}"
  args:
    chdir: "{{bdjuno_dir}}/hasura"
  async: 30
  poll: 10
