---

name: Test Gaia Ansible
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: uname -a
      - run: lsb_release -a
      - run: echo "GitHub branch is ${{ github.ref }}"

      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master

      # install linting
      - run: pip3 install ansible

      # configure inventory
      - run: 'sed 's/root@testnet.com:/localhost:\n          connection: local/g' examples/inventory-local.yml'

      # run Ansible
      - run: ansible-playbook gaia.yml -i inventory.yml
