---

name: Test Gaia Ansible
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get system info
        run: > 
          ifconfig
          sudo dmidecode
          df -h
          free -m
          uname -a
          lsb_release -a
          echo "GitHub branch is ${{ github.ref }}"

      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install Ansible
        run: pip3 install ansible

      - name: Configure inventory
        run: "sed 's/root@testnet.com:/localhost:\\n          connection: local/g' > examples/inventory-local.yml"

      - name: Run playbook
        run: ansible-playbook gaia.yml -i inventory.yml
